/**
* Recipe Puppy
* Recipe Puppy
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package me.pavelsakhanko.shared.models

import kotlinx.serialization.*

/**
 *
 * @param message
 * @param code
 */
@Serializable
data class ErrorModel (
    @SerialName(value = "message") @Required val message: String,
    @SerialName(value = "code") @Required val code: Int
)